/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as RotaRouteImport } from './routes/rota'
import { Route as IdentificarRouteImport } from './routes/identificar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaRoute = RotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentificarRoute = IdentificarRouteImport.update({
  id: '/identificar',
  path: '/identificar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/identificar': typeof IdentificarRoute
  '/rota': typeof RotaRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/identificar': typeof IdentificarRoute
  '/rota': typeof RotaRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/dashboard': typeof DashboardRoute
  '/identificar': typeof IdentificarRoute
  '/rota': typeof RotaRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/identificar'
    | '/rota'
    | '/suporte'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agenda' | '/dashboard' | '/identificar' | '/rota' | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/dashboard'
    | '/identificar'
    | '/rota'
    | '/suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  DashboardRoute: typeof DashboardRoute
  IdentificarRoute: typeof IdentificarRoute
  RotaRoute: typeof RotaRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota': {
      id: '/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof RotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identificar': {
      id: '/identificar'
      path: '/identificar'
      fullPath: '/identificar'
      preLoaderRoute: typeof IdentificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  DashboardRoute: DashboardRoute,
  IdentificarRoute: IdentificarRoute,
  RotaRoute: RotaRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
